= Hibernate Concurrent Update and Quarkus Panache

This repository contains two maven projects that use an in-memory H2 database which is populated when the application starts. They use the `@Version` Hibernate's annotation to detect concurrent updates on the same entity. The two projects are:

- link:1-database-concurrency-plain-hibernate[1-database-concurrency-plain-hibernate]: that uses plain Hibernate with the `@Version` annotation and works just as expected.
- link:2-database-concurrency-panache[2-database-concurrency-panache]: uses Quarkus Panache with the `@Version` annotation, but no `OptimisticLockException` is thrown when two users try to update the same entity.

== Running the projects

Inside the root directory of any of the two projects shown above, type:

[source,bash]
----
./mvnw compile quarkus:dev
----

Then, open two browser tabs at http://localhost:8080/cliente.html?id=1 to update the same entity (simulating to users).
For project #1, an `OptimisticLockException` will be thrown (as expected).
For project #2, it will just overwrite the data on the previous update.
